from __future__ import annotations

import logging
import itertools as it
import glob
import fnmatch
import datetime
import os
from pathlib import Path
from collections import defaultdict

from .file_tools import tarDirectory, tarFiles
from ..utils import getSignal, getCategory, getRecoCategory
from attrs import define
from jinja2 import Environment
import fitting

logger = logging.getLogger("fitting")


@define
class CondorPackage:
    container: str
    transfer_file_list: list[str]
    setup_script: str


RUN_FIT_TEMPLATE = """#!/usr/bin/env bash
# GENERATED AUTOMATICALLY on {{ timestamp }}
echo "STARTING SETUP"


function run_combine {
    local cmd="$1"
    echo $PWD
    echo "RUNNING COMBINE: $cmd"
    apptainer exec --home $_CONDOR_SCRATCH_DIR -B /cvmfs /cvmfs/unpacked.cern.ch/gitlab-registry.cern.ch/cms-analysis/general/combine-container:latest \
        /bin/bash -c "source /cvmfs/cms.cern.ch/cmsset_default.sh && cd /home/cmsusr/CMSSW_14_1_0_pre4 && cmsenv && cd - && $cmd"
}

function run_fit {
    local cmd="$1"
    apptainer exec --home "$_CONDOR_SCRATCH_DIR" {{ container }} /bin/bash -c "source {{ venv_activate_path }} && $cmd"
}


{% for item in files_to_unzip %}
echo "UNTARRING {{item}}"
tar zxf {{ item }}
{% endfor %}
ls -alhtr

export MPLCONFIGDIR=$_CONDOR_SCRATCH_DIR

# Build signal args from pipe-delimited SIGNALS env var
SIG_ARGS=""
IFS='|' read -ra SIG_ARRAY <<< "$SIGNALS"
for s in "${SIG_ARRAY[@]}"; do
    SIG_ARGS="$SIG_ARGS --signal \"$s\""
done

# Resolve output path
ACTUAL_OUTPUT=$(run_fit "python3 -m fitting resolveoutput \
    --background \"$BACKGROUND\" \
    $SIG_ARGS \
    --config \"$CONFIG\" \
    --output-format \"$OUTPUT_DIR_FORMAT\"")

echo "ACTUAL OUTPUT: $ACTUAL_OUTPUT"

run_fit "python3 -m fitting run $SIG_ARGS --background \"$BACKGROUND\" --output \"$OUTPUT_DIR_FORMAT\" --config \"$CONFIG\""

echo "Starting latex build"
LATEX_BUILD_SCRIPT="${ACTUAL_OUTPUT}/_latex_build/build_report.sh"
if [[ -f "$LATEX_BUILD_SCRIPT" ]]; then
    bash "$LATEX_BUILD_SCRIPT"
fi

# Run combine commands if script was generated by COMBINE step


echo "Running combine in \"$PWD\""
COMBINE_SCRIPT="$ACTUAL_OUTPUT/combine/run_combine_commands.sh"
if [ -f "$COMBINE_SCRIPT" ]; then
    echo "Running combine commands from: $COMBINE_SCRIPT"
    bash "$COMBINE_SCRIPT"
    echo "Starting harvest"
    run_fit "python3 -m fitting harvest $ACTUAL_OUTPUT/summary.json"
else
    echo "No combine script found at: $COMBINE_SCRIPT"
fi


"""

SUBMIT_TEMPLATE = """
executable = {{ executable }}
#{% if container %}+ApptainerImage = "{{ container }}"{% endif %}
universe = vanilla
output = {{ output_dir }}/logs/$(cluster)_$(process).out
error = {{ output_dir }}/logs/$(cluster)_$(process).err
log = {{ output_dir }}/logs/$(cluster)_$(process).log
#request_memory = 4GB
request_cpus = 1
transfer_input_files = {{ transfer_input_files | join(', ') }}, $(transfer_signals), $(background)
transfer_output_files = {{ output_dir }}
preserve_relative_paths = True
environment = "CONFIG=$(config) SIGNALS=$(signals) BACKGROUND=$(background) OUTPUT_DIR_FORMAT=$(output_dir_format)"
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

queue transfer_signals, signals, background, output_dir_format, config from (
{%- for job in jobs %}
    {{ job.transfer_signals }}, {{ job.signals }}, {{ job.background }}, {{ job.output_dir }}, {{ job.config }}
{%- endfor %}
)
"""

LOCAL_TEST_TEMPLATE = """#!/usr/bin/env bash
# GENERATED AUTOMATICALLY on {{ timestamp }}
# This script simulates a single HTCondor job execution locally.

TEST_DIR=$(mktemp -d -t condor_test_XXXXXX)
echo "Setting up local test in $TEST_DIR"

echo "Copying transfer files..."
{% for tf in transfer_files %}
if [[ "{{ tf }}" == "{{ executable }}" ]]; then
    cp "{{ tf }}" "$TEST_DIR/"
else
    cp --parents -r "{{ tf }}" "$TEST_DIR/"
fi
{% endfor %}

echo "Copying job-specific files..."
{% for f in job_files %}
cp --parents -r "{{ f }}" "$TEST_DIR/"
{% endfor %}

cd "$TEST_DIR"

export _CONDOR_SCRATCH_DIR="$PWD"
export CONFIG="{{ job.config }}"
export SIGNALS="{{ job.signals }}"
export BACKGROUND="{{ job.background }}"
export OUTPUT_DIR_FORMAT="{{ job.output_dir }}"

echo "Running run_fit.sh..."
./run_fit.sh

echo "Test complete! Check $TEST_DIR for outputs."
"""


def compressNeededFiles(
    venv_path,
    condor_temp_loc,
    extra_files=None,
):
    condor_temp_loc.mkdir(exist_ok=True, parents=True)
    extra_files = extra_files or []
    time_str = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")

    compressed_env = condor_temp_loc / "environment.tar.gz"
    compressed_extra = condor_temp_loc / f"extras_{time_str}.tar.gz"
    compressed_program = condor_temp_loc / f"program_{time_str}.tar.gz"

    program_path = Path(fitting.__file__).parent

    if not compressed_env.exists():
        logger.info(f"Did not find {compressed_env}, creating compressed directory.")
        logger.info(
            "Creating compressed virtual environment. This needs to be done only once."
        )
        tarDirectory(venv_path, compressed_env)

    logger.info("Creating compressed program")
    compressed_extra.unlink(missing_ok=True)
    if extra_files:
        tarFiles(extra_files, compressed_extra)
    tarDirectory(program_path, compressed_program)

    transfer_input_files = [str(compressed_env), str(compressed_program)]
    if extra_files:
        transfer_input_files.append(str(compressed_extra))

    logger.info(f"Needed files: {transfer_input_files}")
    return transfer_input_files


def getJobs(
    signal_pattern: tuple[str, ...],
    background_pattern: str,
    years: list[str],
    pipelines: list[str],
    output_dir: Path,
    config_pattern: str,
    toy_index: int | None = None,
) -> list[dict]:
    jobs = []
    for year, pipeline in it.product(years, pipelines):
        sig_files = set()
        for p in signal_pattern:
            sig_glob = p.replace("{category}", "*")
            sig_glob = sig_glob.format(year=year, pipeline=pipeline)
            sig_files |= set(glob.glob(sig_glob, recursive=True))
        if not sig_files:
            logger.warning(
                f"No signal files found for year {year} with pattern {sig_glob}"
            )
            continue

        for sig_file in sig_files:
            sig_params = getSignal(sig_file)
            category = getCategory(sig_params[1], sig_params[2])
            reco_category = getRecoCategory(Path(sig_file).name)
            if not reco_category:
                continue
            if not any(
                fnmatch.fnmatch(
                    sig_file,
                    x.format(
                        year=year,
                        pipeline=pipeline,
                        category=category,
                        reco_category=reco_category,
                    ),
                )
                for x in signal_pattern
            ):
                continue
            bkg_file = background_pattern.format(
                year=year,
                pipeline=pipeline,
                category=category,
                toy_index=toy_index,
                reco_category=reco_category,
            )
            if not Path(bkg_file).exists():
                raise FileNotFoundError(f"Background file not found: {bkg_file}")
            jobs.append(
                {
                    "signals": sig_file,
                    "transfer_signals": sig_file,
                    "background": bkg_file,
                    "output_dir": output_dir,
                    "category": category,
                    "mstop": sig_params[1],
                    "mchi": sig_params[2],
                    "year": year,
                    "config": config_pattern.format(
                        pipeline=pipeline,
                        category=category,
                        reco_category=reco_category,
                    ),
                }
            )
    return jobs


def groupJobsByMassPoint(jobs: list[dict]) -> list[dict]:
    """Merge single-signal jobs sharing (mstop, mchi, category, background) into multi-signal jobs."""

    groups = defaultdict(list)
    for job in jobs:
        key = (job["mstop"], job["mchi"], job["category"], job["background"])
        groups[key].append(job)

    merged = []
    for key, group in groups.items():
        base = group[0].copy()
        all_signals = [j["signals"] for j in group]
        base["signals"] = "|".join(all_signals)
        base["transfer_signals"] = ", ".join(all_signals)
        merged.append(base)
    return merged


def makeRunFitScript(
    venv_activate_path: str,
    output_dir: str,
    files_to_unzip: list[str],
    container: str | None,
):

    env = Environment()
    template = env.from_string(RUN_FIT_TEMPLATE)
    run_fit_content = template.render(
        files_to_unzip=files_to_unzip,
        venv_activate_path=venv_activate_path,
        container=container,
        timestamp=datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    )

    run_fit_path = output_dir / "run_fit.sh"
    with open(run_fit_path, "w") as f:
        f.write(run_fit_content)
    os.chmod(run_fit_path, 0o755)

    logger.info(f"Run fit script generated at {run_fit_path}")

    return run_fit_path


def makeSubmitScript(
    jobs: list[dict],
    transfer_files: list[str],
    output_dir: str,
    executable: str,
    container: str | None,
):
    env = Environment()
    template = env.from_string(SUBMIT_TEMPLATE)
    submit_content = template.render(
        executable=executable,
        jobs=jobs,
        transfer_input_files=transfer_files,
        output_dir=output_dir,
        container=container,
    )

    submit_path = output_dir / "submit.sub"
    with open(submit_path, "w") as f:
        f.write(submit_content)

    logger.info(f"Submit file generated at {submit_path}")

    return submit_path


def makeLocalTestScript(
    job: dict,
    transfer_files: list[str],
    executable: str,
    output_dir: Path,
):
    env = Environment()
    template = env.from_string(LOCAL_TEST_TEMPLATE)

    job_files = []
    if "transfer_signals" in job:
        job_files.extend([s.strip() for s in job["transfer_signals"].split(",")])
    if "background" in job:
        job_files.append(job["background"])

    test_content = template.render(
        transfer_files=transfer_files,
        job_files=job_files,
        job=job,
        executable=executable,
        timestamp=datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    )

    test_path = output_dir / "local_test.sh"
    with open(test_path, "w") as f:
        f.write(test_content)
    os.chmod(test_path, 0o755)

    logger.info(f"Local test script generated at {test_path}")

    return test_path


def generateCondorSubmit(
    signal_pattern: tuple[str, ...],
    background_pattern: str,
    years: list[str],
    pipelines: list[str],
    config_pattern: str | None = None,
    output_dir: Path = Path("condor_output"),
    subdir_format: str = "{era.name}/{dataset_name}/{injection_rate}",
    venv_path: str | None = None,
    container: str | None = None,
    num_toys: int | None = None,
    multi_signal: bool = False,
) -> None:
    container = (
        container
        or "/cvmfs/unpacked.cern.ch/registry.hub.docker.com/cmsml/cmsml:3.11-cuda"
    )
    output_dir.mkdir(exist_ok=True, parents=True)
    (output_dir / "logs").mkdir(exist_ok=True, parents=True)

    if num_toys is None:
        toys = [0]
    else:
        toys = range(num_toys)
    jobs = []
    for t in toys:
        jobs.extend(
            getJobs(
                signal_pattern,
                background_pattern,
                years,
                pipelines,
                str(output_dir / subdir_format),
                config_pattern,
                toy_index=t,
            )
        )
    if not jobs:
        logger.error("No jobs to submit!")
        return

    if multi_signal:
        jobs = groupJobsByMassPoint(jobs)
        logger.info(f"Grouped into {len(jobs)} multi-signal jobs")

    if not venv_path:
        venv_path = os.environ.get("VIRTUAL_ENV")
        if not venv_path:
            logger.warning(
                "VIRTUAL_ENV not found in environment and not provided. Defaulting to '.venv'."
            )
            venv_path = ".venv"

    configs = list(set(x["config"] for x in jobs))
    transfer_files = compressNeededFiles(
        venv_path=venv_path,
        condor_temp_loc=Path(".condor_temp/"),
        extra_files=configs,
    )

    venv_activate_path = Path(Path(venv_path).name) / "bin" / "activate"

    run_fit_script = makeRunFitScript(
        venv_activate_path,
        output_dir,
        transfer_files,
        container=container,
    )

    transfer_files.append(run_fit_script)

    submit_file_path = makeSubmitScript(
        jobs,
        transfer_files,
        output_dir,
        run_fit_script,
        container=container,
    )

    if jobs:
        makeLocalTestScript(
            jobs[0],
            transfer_files,
            run_fit_script,
            output_dir,
        )

    logger.info(
        f"Condor submit file generated at {submit_file_path} with {len(jobs)} jobs."
    )
