injection_rate: 0.0
min_counts: -1
window_spread: 0
optimization:
  num_iters: 250
  lr: 0.01
  use_map_priors: False
  map_prior_strength: 0
      
model: 
  _type: ExactGPConfig
  kernel: 
    _type: NNWarpingKernelConfig
  likelihood:
    _type: FixedGaussianNoiseConfig
    variance_floor_quantile: 0.5
    
    
