injection_rate: 0.0
optimization:
  num_iters: 250
  lr: 0.01

min_counts: -1

rebin: 2
      
model: 
  _type: ExactGPConfig
  kernel: 
    _type: NNWarpingKernelConfig
  likelihood:
    _type: FixedGaussianNoiseConfig
    variance_floor_quantile: 0.25
    pad_variance_quantile: 0.25
    
