[project]
name = "fittingv1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
 "attrs>=25.4.0",
 "cattrs>=26.1.0",
 "click>=8.3.1",
 "gpjax>=0.13.6",
 "hist>=2.10.1",
 "jax>=0.9.1",
 "lz4>=4.4.5",
 "matplotlib>=3.10.8",
 "mplhep>=1.1.2",
 "numpy>=2.4.3",
 "pyyaml>=6.0.3",
 "rich>=14.3.3",
 "scipy>=1.17.1",
 "uproot>=5.7.2",
]
