injection_rate: 0.0
min_counts: 0

window:
  _type: CoreDilatedWindowConfig
  core_threshold_fraction: 0.5
  dilation_margin: 0.15


optimization:
  mode: sampling
  # objective: loocv
  objective: mll
  num_iters: 250
  optimizer: adam
  lr: 0.025
  mcmc:
    num_samples: 200
    num_warmup: 100
  # restart:
  #   num_restarts: 10
  #   selection:
  #     _type: EnsembleAverageConfig

      
    
# model: 
#   _type: ExactGPConfig
#   kernel: 
#     _type: RationalQuadraticConfig
#   likelihood:
#     _type: FixedGaussianNoiseConfig
#     variance_floor_quantile: 0.05
#     pad_variance_quantile: 0.0
#   mean_function:
#     _type: ConstantMeanConfig

# model: 
#   _type: ExactGPConfig
#   kernel: 
#     _type: RationalQuadraticConfig
#   likelihood:
#     _type: FixedGaussianNoiseConfig
#     variance_floor_quantile: 0.05
#     pad_variance_quantile: 0.0
#   mean_function:
#     _type: NeuralMeanConfig
#     hidden_shapes: [20,20]

# model: 
#   _type: ExactGPConfig
#   kernel: 
#     _type: NNWarpingKernelConfig
#     hidden_shapes: [5,5]
#     #activation: tanh
#   likelihood:
#     _type: FixedGaussianNoiseConfig
#     variance_floor_quantile: 0.05
#     #scale_variance_value: 2
#     # pad_variance_quantile: 0.25
#   # mean_function:
#   #   _type: ConstantMeanConfig
#   mean_function:
#     _type: NeuralMeanConfig
#     hidden_shapes: [5,5]

# model: 
#   _type: ExactGPConfig
#   kernel: 
#     _type: BinIntegratedKernelConfig
#     n_quad: 3
#     base_kernel:
#       _type: NNWarpingKernelConfig
#       hidden_shapes: [5,5]
#     #activation: tanh
#   likelihood:
#     _type: FixedGaussianNoiseConfig
#     variance_floor_quantile: 0.05
#     #scale_variance_value: 2
#     # pad_variance_quantile: 0.25
#   # mean_function:
#   #   _type: ConstantMeanConfig
#   mean_function:
#     _type: NeuralMeanConfig
#     hidden_shapes: [5,5]


model:
  _type: ExactGPConfig
  kernel:
    _type: NNWarpingKernelConfig
    hidden_shapes: [5,5]
    weight_prior:
      _type: NormalPriorConfig
      loc: 0.0
      scale: 1.0
    bias_prior:
      _type: NormalPriorConfig
      loc: 0.0
      scale: 1.0
    base_kernel_config:
      _type: RBFConfig
      lengthscale_prior:
        _type: LogNormalPriorConfig
        loc: -2.3
        scale: 1.0
      variance_prior:
        _type: LogNormalPriorConfig
        loc: -0.7
        scale: 1.0
  mean_function:
    _type: ConstantMeanConfig
    # _type: NeuralMeanConfig
    # hidden_shapes: [5,5]
    # weight_prior:
    #   _type: NormalPriorConfig
    #   loc: 0.0
    #   scale: 1.0
    # bias_prior:
    #   _type: NormalPriorConfig
    #   loc: 0.0
    #   scale: 1.0