injection_rate: 0.0
min_counts: -1
rebin: 1

window:
  _type: CoreDilatedWindowConfig
  core_threshold_fraction: 0.5
  dilation_margin: 0.15


optimization:
  mode: optimization
  objective: mll
  num_iters: 250
  lr: 0.01
  optimizer: "adam"
  restart:
    num_restarts: 3
    strategy:
      _type: ResampleConfig
    criterion:
      _type: AlwaysContinueConfig
    selection:
      _type: BestLossConfig


domain_window:
  _type: AndWindowConfig
  windows:
    - _type: FunctionSliceWindowConfig
      expression: "y < (np.sqrt(0.003 * x / 2500) + 0.935)"
    - _type: FunctionSliceWindowConfig
      expression: "y > 0.9"

model:
  _type: ExactGPConfig
  kernel:
    _type: SumKernelConfig
    kernels:
    - _type: NNWarpingKernelConfig
      hidden_shapes: [20,20]
      activation: "selu"
      base_kernel_config:
        _type: RBFConfig
        ard: true
    # - _type: NNTransformKernelConfig
    #   hidden_shapes: [20]
    #   base_kernel_config:
    #     _type: Matern32Config
    #     ard: true
    # - _type: WhiteConfig
    #   variance: 0.005
  likelihood:
    _type: FixedGaussianNoiseConfig
    variance_floor_quantile: 0.05
    # pad_variance_quantile: 0.25
  mean_function:
    _type: ConstantMeanConfig
