injection_rate: 0.0
min_counts: -1
rebin: 2

window:
  _type: CoreDilatedWindowConfig
  core_threshold_fraction: 0.5
  dilation_margin: 0.2


optimization:
  mode: optimization
  objective: loocv
  num_iters: 250
  lr: 0.01

model: 
  _type: ExactGPConfig
  kernel: 
    _type: NNWarpingKernelConfig
    hidden_shapes: [20,20]
  likelihood:
    _type: FixedGaussianNoiseConfig
    variance_floor_quantile: 0.05
    #pad_variance_quantile: 0.5
  mean_function:
    _type: ZeroMeanConfig
