injection_rate: 0.0
min_counts: -1
window_spread: 0
optimization:
  num_iters: 250
  lr: 0.01
model:
  _type: MultiFidelityGPConfig
  mc_path: "/uscms/home/ckapsiak/nobackup/Analysis/SingleStop/FittingV1/smoothed/2018/Signal312/qcd_inclusive_2018/uncomp/smoothed_uncomp.pklz4"
  mc_kernel:
    _type: RBFConfig
    ard: true
  mc_num_iters: 150
  mc_lr: 0.01
  residual_kernel:
    _type: NNKernelConfig
  learn_rho: true
  propagate_mc_variance: true
  likelihood:
    _type: FixedGaussianNoiseConfig
    variance_floor_quantile: 0.5
