injection_rate: 0.0
min_counts: 0.0
rebin: 2

window:
  _type: CoreDilatedWindowConfig
  core_threshold_fraction: 0.5
  dilation_margin: 0.15

transform:
  _type: StandardizationConfig

optimization:
  mode: optimization
  objective: mll
  num_iters: 250
  lr: 0.01
  restart:
    num_restarts: 3
    strategy:
      _type: ResampleConfig
    criterion:
      _type: AlwaysContinueConfig
    selection:
      _type: BestLossConfig

model: 
  _type: ExactGPConfig
  kernel: 
    _type: NNWarpingKernelConfig
    hidden_shapes: [20,20]
  likelihood:
    _type: FixedGaussianNoiseConfig
    variance_floor_quantile: 0.05
    # pad_variance_quantile: 0.25
  mean_function:
    _type: ConstantMeanConfig

# model: 
#   _type: ExactGPConfig
# 
#   kernel: 
#     _type: SumKernelConfig
#     kernels:
#       - _type: NNWarpingKernelConfig
#         hidden_shapes: [20,20]
#       - _type: HeteroscedasticWhiteConfig
#   likelihood:
#     _type: FixedGaussianNoiseConfig
#     variance_floor_quantile: 0.01
#   mean_function:
#     _type: ConstantMeanConfig
