injection_rate: 0.0
min_counts: 0
rebin: 2
window:
  core_threshold_fraction: 0.4
  smooth_sigma: 1.5
  dilation_margin: 0.25
  background_expression: +2.3290237 * 1 - 0.76967804 * y - 0.73164295 * y**2 + +0.45308722
    * y**3 - 0.73374446 * y**4 - 2.1175875 * x - 0.17125079 * x * y + +0.88467392
    * x * y**2 + +0.028024427 * x * y**3 - 0.27737511 * x**2 - 0.16770753 * x**2 *
    y + +0.35622941 * x**2 * y**2 + +1.1551633 * x**3 + +0.43777287 * x**3 * y - 1.0177994
    * x**4
  background_x_lo:
  - 750.0
  - 0.1
  background_x_hi:
  - 2500.0
  - 0.8
  _type: SignificanceThresholdWindowConfig
transform:
  _type: StandardizationConfig
optimization:
  mode: optimization
  objective: mll
  num_iters: 250
  lr: 0.025
model:
  _type: ExactGPConfig
  kernel:
    _type: NNWarpingKernelConfig
    hidden_shapes:
    - 20
    - 20
  likelihood:
    _type: FixedGaussianNoiseConfig
    variance_floor_quantile: 0.05
  mean_function:
    _type: ConstantMeanConfig
